# Generated by Django 4.0.6 on 2022-07-10 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='decription',
            new_name='description',
        ),
    ]
